name: tasker
description: A TODO list app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: TTFirsNeue
      fonts:
        - asset: assets/fonts/TTFirsNeue-Bold.ttf
